### ISSUE TITLE
Duplicate class com.google.android.play.core.appupdate.AppUpdateInfo

### ISSUE THREAD

**Issue by waperp** [jonasbark/flutter_in_app_update#89]
I got this error, when i upgraded from version 3.0.0 to 4.0.1.
I get the photo error.

```
What went wrong:
Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.play.core.appupdate.AppUpdateInfo found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateManager found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateManagerFactory found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateOptions found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateOptions$Builder found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.appupdate.testing.FakeAppUpdateManager found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.common.IntentSenderForResultStarter found in modules jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.common.LocalTestingException found in modules jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.common.PlayCoreDialogWrapperActivity found in modules jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.install.InstallException found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.install.InstallState found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
Duplicate class com.google.android.play.core.install.InstallStateUpdatedListener found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.install.NativeInstallStateUpdateListener found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.install.model.ActivityResult found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.install.model.AppUpdateType found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.install.model.InstallErrorCode found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.install.model.InstallStatus found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.install.model.UpdateAvailability found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1)
     Duplicate class com.google.android.play.core.listener.StateUpdatedListener found in modules jetified-core-1.9.1-runtime (com.google.android.play:core:1.9.1) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Exception: Gradle task assembleDevDebug failed with exit code 1
```

![image](https://user-images.githubusercontent.com/44144275/204573659-b55ab58c-9fab-40f7-9b13-a207f712c6ee.png)

**Comment by waperp** [comment]
@jonasbark  help plis!

**Comment by jonasbark** [comment]
https://github.com/jonasbark/flutter_in_app_update/issues/84

**Comment by waperp** [comment]
@jonasbark 

I can't solve it and I'm going 3 days, I don't know what bookstore could be causing this? maybe you could give me a help hint? Cheers

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.5
  timeago: ^3.3.0
  path: ^1.8.1
  package_info_plus: ^3.0.2
  double_back_to_close_app:
    path: ./packages/double_back_to_close_app-master
  equatable: ^2.0.5
  webview_flutter: ^3.0.4
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  flutter_polyline_points: ^1.0.0
  camera: ^0.10.0+4
  hive: ^2.2.3
  path_provider: ^2.0.11
  flutter_rating_bar:
    path: ./packages/flutter_rating_bar-master
  cron: ^0.5.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^14.1.3
  firebase_dynamic_links: ^5.0.7
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  amplify_flutter: ^0.6.10
  amplify_auth_cognito: ^0.6.10
  amplify_storage_s3: ^0.6.10
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  in_app_update: ^3.0.0
  flutter_image_compress: ^1.1.3
  image_picker: ^0.8.6
  mime: ^1.0.2
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.2.1
  smooth_page_indicator:
    path: ./packages/smooth_page_indicator-master
  sizer: ^2.0.15
  flutter_background_geolocation: ^4.8.3
  background_fetch: ^1.1.2
  permission_handler: ^10.2.0
  intl: ^0.17.0-nullsafety.2
  file_picker: ^5.2.3
  multi_select_flutter:
    path: ./packages/multi_select_flutter-master
  percent_indicator: ^4.2.2
  pull_to_refresh:
    path: ./packages/pull_to_refresh-master
  pin_code_fields:
    path: ./packages/pin_code_fields-master
  flutter_dotenv: ^5.0.2
  collection: ^1.16.0
  pusher_client: ^2.0.0
  easy_mask: ^2.0.1
  sentry_flutter: ^6.17.0
  vector_math: ^2.1.2
  uuid: ^3.0.6
  restart_app: ^1.1.1
  internet_connection_checker: ^1.0.0+1
```
